CREATE TABLE BOOKS(
  ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) DEFAULT NULL,
  AUTHOR VARCHAR(255) DEFAULT NULL,
  ISBN VARCHAR(255) DEFAULT NULL,

  STATUS TINYINT DEFAULT 1,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);